cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}

network.host: ${NETWORK_HOST}

path:
  data: /data/data
  logs: /data/log
  plugins: /elasticsearch/plugins
  work: /data/work

bootstrap.mlockall: true

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

cloud:
  aws:
    access_key: ${AWS_KEY}
    secret_key: ${AWS_SECRET}

discovery:
  type: ec2
  ec2.tag:
    ${TAG_KEY}: ${TAG_VALUE}
  zen:
    minimum_master_nodes: ${NUMBER_OF_MASTERS}

index:
    number_of_shards: ${NUMBER_OF_SHARDS}
    number_of_replicas: ${NUMBER_OF_REPLICAS}